using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace SpiritMod.Items.Books
{
    class Book_Amea : Book
    {
        public override string BookText => "At the edge of the kingdom's borders lay a small cottage, surrounded by acres of forest. It was a small dwelling, home to a poor, middle-aged woman and her young son, Amea. The family was destitute and quite alone, but Amea's mother had been saving up money for years so that Amea could finally go to school and become a merchant. Upon giving the money to Amea, he became distraught. He did not want to leave his mother alone in the forest, but he soon relented. His mother did not want to see him follow the same path as she did. And so, Amea set off on his way to the small school nearby.\n\n---\n\nAs it turns out, Amea was a smart and hardworking student. He had simply never been given the opportunity before. He was kind, helpful, and determined to succeed so that he could return home to his mother with riches in hand. He soon became his teacher's favorite, much to the dismay of his classmates. They soon grew to hate him, filled with jealousy and ire. His classmates then hatched a devious plan to turn their teacher against Amea. They slowly poisoned the teacher's mind with stray whispers and rumors, painting Amea as a cruel savage. The teacher fell into their trap, and so too did he begin to hate Amea. On the last day of teaching, when students were to receive their recommendations from their teacher to join different guilds, Amea was blindsided by a gruesome request from his teacher.\n\n'In order to receive my recommendation, you must first bring me the pointer fingers of one thousand people. Otherwise, you will never be able to join the merchant guild you seek,' said he. Amea was taken aback by this horrifying task. He was not aware that everyone he knew despised him. But Amea needed to provide for his family.\n\nAnd so he set off on this task.\n\n---\n\n" +
            "Amea used some of his money to buy a rusty sword, and made a camp in the middle of the woods. At first, he was too scared to carry out this vile mission. Amea was a kind man who wished no ill will on anyone, including the teacher who had assigned him this task. But he thought of his mother at home and swallowed his fear. And so it began. Amea stopped one traveller after another and cut off their fingers. Upon collecting too many to carry, Amea tried to bury them in the ground. But they either decomposed or were eaten by crows and vultures. Amea then decided to string the fingers on a garland and wear them. His infamy grew over time, and he was soon known as 'The Bandit with the Finger Necklace.' Amea was changing.\n\n---\n\n" +
            "The once bright and kind student was no more. Amea relished in violence, and grew exceedingly cruel to his victims. The amount of fingers on his garland grew. He soon stole from and maimed his victims on top of dismembering them, and became the most feared bandit in the kingdom. Many squads of soldiers were sent into the forests to end Amea's reign of terror, but returned battered, empty-handed, and fingerless.\n\n---\n\nAfter years of ravaging the kingdom, the fateful day soon arrived when Amea had nine hundred ninety-nine fingers on his garland. He planned on returning to his teacher laden with fingers and then killing him before returning to the life of a brigand. This was Amea's path now. An unsuspecting ox-cart made its way through the forest, and Amea lay waiting in the trees. When the time was right, he jumped down and slashed the throat of the cart driver, quickly taking his finger. But no one screamed. Confused by the lack of panic, Amea turned around to see a lone woman sitting in the cart, looking at him with sheer horror, revulsion, and- most of all- disappointment. It was his mother. Amea opened his mouth, but could not speak. His mother said no words to him, but tears started cascading down her old and weary face. She was gaunt and looked starved, not having enough money to eat properly. Amea said nothing, and retreated deep into the woods. He found a clear pond and gazed into it. He saw what he had become: a wild savage draped in human fingers. He could scarcely recognize himself anymore. A sudden wave of shame and horror crashed down upon Amea. Sick to the stomach, he renounced his banditry and led a reclusive life within a cave in the woods." +
            "\n\n---\n\nFor years, people in the kingdom steered clear of Amea's woods. Nobody knew where the bandit had gone, but no one wanted to be his next victim. That was until a great wizard arrived at the kingdom. This sage was well known for spreading teachings of peace to those who wanted to listen. He had overheard rumors about Amea, and was curious to meet the man. The citizens of the kingdom warned him not to journey into the woods, but the wizard chose to do so anyway. He walked into the woods without a staff or any weapon, carefree as could be.\n\n" +
            "Amea soon heard footsteps from outside his cave and quickly grew angry that someone dared to disturb his solitude. He drew his sword and emerged from the cave to see the wizard nonchalantly walking away from him.\n\n'You there!' Amea bellowed. 'Stop moving and surrender yourself.'\n\nThe wizard kept walking.\n\nFurious, Amea chased after the mystic at full speed. Try as he might, though, he could never catch up. The wizard, walking slowly and calmly, always stayed ahead of Amea. Amea howled and kept running for what felt like days. The wizard did not say a word. Finally, Amea gave up. He dropped to his hands and knees and begged for the wizard to forgive him. A sudden outpouring of remorse and pain emerged from Amea, who wanted nothing more than to leave his past behind. But how could a killer ever escape his sins?\n\nThe wizard, sensing these emotions, turned to Amea and uttered his first words.\n\n'We are all born heedless, and some of us choose to return to that state. But what makes us human is our capacity to grow and change.'\n\nThe wizard stopped moving, and reached his hand out to Amea. Amea found that he could finally approach the wizard. For the first time in years, Amea put down his sword. He took the mystic's hand and walked out of the forest into the light of day.";

        public override void SetStaticDefaults()
        {
            DisplayName.SetDefault("Amea the Brigand");
            Tooltip.SetDefault("by Solaki");
        }
    }
}