using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpiritMod.Mechanics.QuestSystem
{
	public class QuestTask
	{
		public bool Completed { get; set; }
		public int TaskID { get; set; }
		public QuestTask NextTask { get; set; }

		// used to allow us to override what the objective displays as.
		public string ObjectiveTextOverrideHUD { get; set; }
		public string ObjectiveTextOverrideBook { get; set; }

		public QuestTask()
		{
			ObjectiveTextOverrideBook = null;
			ObjectiveTextOverrideHUD = null;
		}

		public void GetBookText(List<string> lines)
		{
			if (ObjectiveTextOverrideBook != null)
			{
				lines.Add(ObjectiveTextOverrideBook);
				return;
			}

			AutogeneratedBookText(lines);
		}

		public void GetHUDText(List<string> lines)
		{
			if (ObjectiveTextOverrideHUD != null)
			{
				lines.Add(ObjectiveTextOverrideHUD);
				return;
			}

			AutogeneratedHUDText(lines);
		}

		public virtual string ModCallName => "";
		public virtual QuestTask Parse(object[] args) { throw new NotImplementedException(); }

		public virtual bool CheckCompletion() { return true; }
		public virtual void Activate() { }
		public virtual void Deactivate() { }
		public virtual void OnMPSyncTick() { }
		public virtual void ResetProgress() { Completed = false; }
		public virtual void AutogeneratedBookText(List<string> lines) { }
		public virtual void AutogeneratedHUDText(List<string> lines) { }
	}
}
